
---
- name: Remove educational packages
  ansible.builtin.apt:
    name: "{{ edu_packages }}"
    purge: yes
    state: absent
  become: yes
  notify: autoremove

- name: Remove Java packages
  ansible.builtin.apt:
    name: "{{ java_packages }}"
    purge: yes
    state: absent
  become: yes
  notify: autoremove

- name: Remove Python packages
  ansible.builtin.apt:
    name: "{{ python_packages }}"
    purge: yes
    state: absent
  become: yes
  notify: autoremove

- name: Remove misc packages
  ansible.builtin.apt:
    name: "{{ misc_packages }}"
    purge: yes
    state: absent
  become: yes
  notify: autoremove
...
