---
- name: Open Real Time Streaming port for AirPlay
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ shairport_tcp_port }}"
    proto: tcp
    src: "{{ item }}"
    loop: "{{ private_local_addresses }}"

- name: Open mDNS port for AirPlay
  community.general.ufw:
    rule: allow
    direction: in
    port: 5353
    proto: udp
    src: "{{ item }}"
    loop: "{{ private_local_addresses }}"

- name: Open ports for shairport-sync for AirPlay
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ shairport_ports }}"
    proto: udp
    src: "{{ item }}"
    loop: "{{ private_local_addresses }}"

- name: Install shairport-sync dependencies
  ansible.builtin.apt:
    name: "{{ shairport_dep_packages }}"
    status: latest

- name: Create shairport-sync group
  ansible.builtin.group:
    name: shairport-sync
    system: yes
    state: present

- name: Create shairport-sync user
  ansible.builtin.user:
    name: shairport-sync
    shell: /usr/bin/nologin
    system: yes
    create_home: no
    group: shairport-sync
    groups: audio
    append: yes
    state: present

- name: Create shairport-sync directory
  ansible.builtin.file:
    path: "{{ shairport_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Clone shairport-sync
  ansible.builtin.git:
    repo: https://github.com/mikebrady/shairport-sync.git
    dest: "{{ shairport_dir }}"
    version: "{{ shairport_version }}"
    depth: 1

- name: Generate build system files for shairport-sync
  ansible.builtin.command: autoreconf -fi
  args:
    chdir: "{{ shairport_dir }}"
  become: yes

- name: Configure build for shairport-sync
  ansible.builtin.command: ./configure --sysconfdir=/etc --with-alsa --with-soxr --with-avahi --with-ssl=openssl --with-systemd
  args:
    chdir: "{{ shairport_dir }}"
  become: yes

- name: Build shairport-sync
  ansible.builtin.command: make
  args:
    chdir: "{{ shairport_dir }}"
  become: yes

- name: Install shairport-sync
  ansible.builtin.command: make install
  args:
    chdir: "{{ shairport_dir }}"
  become: yes

- name: Enable shareport-sync
  ansible.builtin.systemd:
    become: yes
    name: shairport-sync.service
    enabled: yes
    state: restarted
...
