---
- name: restart avahi service
  ansible.builtin.systemd:
    name: avahi-daemon.service
    daemon_reload: yes
    enabled: yes
    state: restarted
  become: yes

- name: Restart dhcpcd service
  ansible.builtin.systemd:
    name: dhcpcd.service
    enabled: yes
    state: restarted
  become: yes
...
