---
- name: Restart dhcpcd service
  ansible.builtin.systemd:
    name: dhcpcd.service
    enabled: yes
    state: restarted
  become: yes

- name: Restart fail2ban service
  ansible.builtin.systemd:
    name: fail2ban.service
    enabled: yes
    state: restarted
  become: yes

- name: Restart sshd service
  ansible.builtin.systemd:
    name: sshd.service
    enabled: yes
    state: restarted
  become: yes
...
