---
- name: Remove GUI packages
  ansible.builtin.apt:
    name: "{{ gui_packages }}"
    purge: yes
    state: absent
  notify: autoremove

- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: present

- name: Advertise SSH Service via Avahi
  ansible.builtin.template:
    src: templates/ssh.service.j2
    dest: /etc/avahi/services/ssh.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart avahi service

- name: Boot into text console mode, without auto-login
  ansible.builtin.command: raspi-config nonint do_boot_behaviour B1
  notify: reboot

- name: Set GPU memory to 16 MB
  ansible.builtin.command: raspi-config nonint do_memory_split 16
  notify: reboot

- name: Disable camera interface
  ansible.builtin.command: raspi-config nonint do_camera 1

- name: Disable the VNC Server
  ansible.builtin.command: raspi-config nonint do_vnc 1

- name: Disable SPI
  ansible.builtin.command: raspi-config nonint do_spi 1

- name: Disable I2C
  ansible.builtin.command: raspi-config nonint do_i2c 1

- name: Disable Serial interface
  ansible.builtin.command: raspi-config nonint do_serial 1

- name: Disable 1-wire
  ansible.builtin.command: raspi-config nonint do_onewire 1

- name: Disable remote GPIO
  ansible.builtin.command: raspi-config nonint do_rgpio 1

- name: Turn off the power LED at night
  ansible.builtin.cron:
    minute: "00"
    hour: "20"
    job: "echo 0 > /sys/class/leds/led1/brightness"
    user: root
  notify: reboot

- name: Turn on the power LED in the morning
  ansible.builtin.cron:
    minute: "00"
    hour: "08"
    job: "echo 1 > /sys/class/leds/led1/brightness"
    user: root
  notify: reboot

- name: Turn off the power LED after reboot
  ansible.builtin.cron:
    special_time: reboot
    job: "echo 0 > /sys/class/leds/led1/brightness"
    user: root
  notify: reboot
...
