---
- name: restart networkmanager
  ansible.builtin.systemd:
    name: networkmanager
    enabled: yes
    state: restarted
  become: yes

- name: restart tmp.mount
  ansible.builtin.systemd:
    name: tmp.mount
    enabled: yes
    state: restarted
  become: yes

- name: restart log2ram
  ansible.builtin.systemd:
    name: log2ram
    enabled: yes
    state: restarted
  become: yes

- name: restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    enabled: yes
    state: restarted
  become: yes
...
