---
- name: restart tmp.mount
  ansible.builtin.systemd:
    name: tmp.mount
    enabled: yes
    state: restarted
  become: yes

- name: restart log2ram
  ansible.builtin.systemd:
    name: log2ram
    enabled: yes
    state: restarted
  become: yes

  ansible.builtin.systemd:
    enabled: yes
    state: restarted
...
