---
- name: Checking if Realtek 8192 driver loaded
  ansible.builtin.shell: lsmod | grep 8192
  register: lsmod_8192
  failed_when: lsmod_8192.rc == 2
  changed_when: false

- set_fact:
  loaded_8192_driver: {{ lsmod_8192.rc == 0 }}

- name: Disabling WiFi power saving
  become: yes
  ansible.builtin.template:
    src: templates/8192.conf.j2
    dest: /etc/modprobe.d/8192.conf
    owner: root
    group: root
    mode: "0644"
  when: loaded_8192_driver
...
