---
- name: Remove onboard sound driver
  ansible.builtin.lineinfile:
    dest: /boot/config.txt
    state: absent
    regexp: "^dtparam=audio=on"
  notify: reboot

- name: Disable vc4-fkms-3d
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^dtoverlay=vc4-fkms-v3d'
    line: dtoverlay=vc4-fkms-v3d,audio=off
  notify: reboot

- name: Disable vc4-kms-3d
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^dtoverlay=vc4-kms-v3d'
    line: dtoverlay=vc4-kms-v3d,noaudio
  notify: reboot

- name: Enable Dac+
  ansible.builtin.lineinfile:
    dest: /boot/config.txt
    line: "dtoverlay=hifiberry-dacplus"
    state: present
  notify: reboot

- name: Configure alsa
  ansible.builtin.template:
    src: templates/asound.conf.j2
    dest: /etc/asound.conf
    owner: root
    group: root
    mode: "0644"
  notify: reboot

- name: Turn off HiFi Berry DAC lights after boot
  ansible.builtin.lineinfile:
    dest: /etc/rc.local
    line: (sleep 10 && amixer -q set Digital 0% && aplay -q -D sysdefault -c 2 /usr/share/sounds/alsa/Noise.wav; amixer -q set Digital 100%) &
    state: present
  notify: reboot
...
