---
gui_packages:
  - xserver-xorg-video-fbdev
  - xserver-xorg
  - xinit
  - gstreamer1.0-x
  - gstreamer1.0-omx
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-alsa
  - gstreamer1.0-libav
  - epiphany-browser
  - lxde
  - lxtask
  - menu-xdg
  - gksu
  - xserver-xorg-video-fbturbo
  - xpdf
  - gtk2-engines
  - netsurf-gtk
  - zenity
  - desktop-base
  - lxpolkit
  - weston
  - omxplayer
  - raspberrypi-artwork
  - lightdm
  - gnome-themes-standard-data
  - gnome-icon-theme
  - qt50-snapshot
  - qt50-quick-particle-examples
...
