---
- name: Check if Realtek 8192 driver loaded
  ansible.builtin.shell: lsmod | grep -e '^8192cu'
  ignore_errors: true
  register: lsmod_8192cu
  failed_when: lsmod_8192cu.rc == 2

- ansible.builtin.set_fact:
    loaded_8192_driver: "{{ lsmod_8192cu.rc == 0 }}"

- name: Disable WiFi power saving for Realtek 8192cu
  become: yes
  ansible.builtin.template:
    src: templates/8192cu.conf.j2
    dest: /etc/modprobe.d/8192cu.conf
    owner: root
    group: root
    mode: "0644"
  when: loaded_8192_driver

- name: Disable WiFi power saving for interfaces
  become: yes
  ansible.builtin.template:
    src: templates/wireless-power-off.j2
    dest: /etc/network/interfaces.d/wireless-power-off
    owner: root
    group: root
    mode: "0644"

- name: Disable WiFi power saving in NetworkManager
  become: yes
  ansible.builtin.template:
    src: templates/wifi.powersave-off.conf.j2
    dest: /etc/NetworkManager/conf.d/wifi.powersave-off.conf
    owner: root
    group: root
    mode: "0644"

- name: Check for tmp.mount systemd unit
  ansible.builtin.shell: systemctl status tmp.mount
  register: tmpmount_status
  become: yes
  failed_when: tmpmount_status.rc > 4

- ansible.builtin.set_fact:
    tmpmount_missing: "{{ tmpmount_status.rc == 4 }}"

- name: Install tmp.mount systemd unit
  ansible.builtin.shell: systemctl enable /usr/share/systemd/tmp.mount
  become: yes
  when: tmpmount_missing

- name: Enable tmp.mount
  ansible.builtin.systemd:
    name: tmp.mount
    enabled: yes
    state: started
  become: yes
  notify: reboot

- name: Create tmp.mount config directory
  ansible.builtin.file:
    path: /etc/systemd/system/tmp.mount.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure tmp.mount
  ansible.builtin.template:
    src: templates/size.conf.j2
    dest: /etc/systemd/system/tmp.mount.d/size.conf
    owner: root
    group: root
    mode: 0644
  notify: restart tmp.mount

- name: Create systemd-journald overrides directory
  file:
    path: /etc/systemd/journald.conf.d/
    state: directory
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Limit /var/log/journal size
  ansible.builtin.template:
    src: templates/00-journal-size.conf.j2
    dest: /etc/systemd/journald.conf.d/00-journal-size.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart journald

- name: Disable rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    enabled: no
    state: stopped
  become: yes

- name: Install log2ram dependencies
  ansible.builtin.apt:
    name: "{{ log2ram_dep_packages }}"
    state: latest

- name: Create log2ram directory
  ansible.builtin.file:
    path: "{{ log2ram_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Clone log2ram
  ansible.builtin.git:
    repo: https://github.com/azlux/log2ram.git
    dest: "{{ log2ram_dir }}"
    version: "{{ log2ram_version }}"
    depth: 1
  register: log2ram_clone

- name: Check if log2ram installed
  ansible.builtin.shell: systemctl status log2ram
  register: log2ram_status
  become: yes
  failed_when: log2ram_status.rc > 4

- ansible.builtin.set_fact:
    log2ram_installed: "{{ log2ram_status.rc != 4 }}"

- name: Disable log2ram
  ansible.builtin.systemd:
    name: log2ram
    enabled: no
    state: stopped
  when: log2ram_clone.changed and log2ram_installed

- name: Install log2ram
  ansible.builtin.command:
    chdir: "{{ log2ram_dir }}"
    cmd: "sh -e {{ log2ram_dir }}/install.sh"
  when: not log2ram_installed

- name: Set log2ram reserved size in RAM
  ansible.builtin.lineinfile:
    path: /etc/log2ram.conf
    regexp: "^SIZE="
    line: "SIZE=100M"
  notify: restart log2ram

- name: Set log2ram mailer off
  ansible.builtin.lineinfile:
    path: /etc/log2ram.conf
    regexp: "^MAIL="
    line: "MAIL=false"
  notify: restart log2ram

- name: Set log2ram write to disk to weekly on Mondays
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/log2ram-daily.timer
    regex: "^OnCalendar="
    line: "OnCalendar=Mon *-*-* 05:00:00"
    state: present
  notify: restart log2ram

- name: Disable swap
  ansible.builtin.command: dphys-swapfile swapoff

- name: Uninstall dphys-swapfile
  ansible.builtin.command: dphys-swapfile uninstall

- name: Stop and disable dphys-swapfile service
  ansible.builtin.systemd:
    name: dphys-swapfile
    enabled: no
    state: stopped
  notify: reboot
...
