---
- name: Remove default pi user
  ansible.builtin.user:
    name: pi
    remove: yes
    state: absent
  when: ansible_user_id != "pi"
  notify: reboot

- name: Configure sshd
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: "/usr/sbin/sshd -T -f %s"
  notify: Restart sshd service

- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: latest

- name: Allow access from private (RFC1918) and link-local networks over SSH
  community.general.ufw:
    state: enabled
    rule: allow
    direction: in
    port: 22
    proto: tcp
    src: "{{ item }}"
  loop: "{{ private_local_addresses }}"

- name: Allow IPv4 mDNS multicast traffic
  community.general.ufw:
    state: enabled
    rule: allow
    direction: in
    port: 5353
    proto: udp
    dest: 224.0.0.251
    src: "{{ item }}"
  loop: "{{ private_local_addresses }}"

- name: Allow IPv6 mDNS multicast traffic
  community.general.ufw:
    state: enabled
    rule: allow
    direction: in
    port: 5353
    proto: udp
    dest: ff02::fb
    src: "{{ item }}"
  loop: "{{ private_local_addresses }}"

- name: Deny everything else, set low logging
  community.general.ufw:
    state: enabled
    direction: incoming
    default: deny
    logging: low

- name: Harden against common network attack vectors
  ansible.builtin.template:
    src: templates/sysctl-local.conf.j2
    dest: /etc/sysctl.d/local.conf
    owner: root
    group: root
    mode: "0644"

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: latest

- name: Configure fail2ban
  ansible.builtin.template:
    src: templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban service

- name: Set DNS servers
  ansible.builtin.lineinfile:
    path: /etc/dhcpcd.conf
    regex: "domain_name_servers="
    line: "static domain_name_servers=1.1.1.1 1.0.0.1"
    state: present
  notify: Restart dhcpcd service

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: latest

- name: Configure APT auto-upgrades
  ansible.builtin.template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Configure unattended-upgrades
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
...
